### ISSUE TITLE
package validator

### ISSUE THREAD

**Issue by fanatid** [ethereumjs/keythereum#23]
`isHexadecimal` looks not good _for us_ https://github.com/chriso/validator.js/issues/648
Is keys by geth can be encoded with base64?

should we implement own validators and remove this package?

**Comment by tinybike** [comment]
Good find.  It seems simplest to follow the recommendation to use `str.length % 2 == 0 && validator.isHexadecimal(str)`.  Or, are there other issues with this library?

Re: base64, no it isn't normally used in Ethereum.  I've considered removing base64 support altogether but it's been around a while and someone may be using it, so I've kept it in for now...
