### ISSUE TITLE
browserifiable version

### ISSUE THREAD

**Issue by fanatid** [ethereumjs/keythereum#27]
https://github.com/ethereumjs/keythereum/blob/0.4.7/index.js#L8-L11

- why `NODE_JS` defined as `(typeof module !== "undefined") && process && !process.browser`? not just `process.browser`?
- instead `var path = (NODE_JS) ? require("path") : null;` will better resolve through `browser` field in `package.json`

**Comment by tinybike** [comment]
Read a bit about this today and it seems there is not a consensus on the best way to detect Node.js vs browser environment.  Apparently browserify and webpack are the edge cases that create complications.  I thought [this discussion](https://github.com/Microsoft/TypeScript/issues/3488) was good -- conclusion was that the "right" way to do this is:
```javascript
typeof process !== "undefined" && process.nextTick && !process.browser
```

**Comment by fanatid** [comment]
`nextTick` is defined in [process](https://github.com/defunctzombie/node-process/blob/v0.11.9/browser.js#L134) for browser

**Comment by tinybike** [comment]
Well, `process.nextTick` is defined if you `require('process')`, but the browser does not normally have `process.nextTick` (or `process`) defined.
