### ISSUE TITLE
Create several accounts

### ISSUE THREAD

**Issue by aemet93** [ethereumjs/keythereum#38]
Hi there,
how can I create several accounts and import/export it? For example Mist allow to store many accounts.

**Comment by cryst10** [comment]
Hi, ```keythereum.create()``` generates a private key, so can it also generate a public key? maybe it does but I am not entirely sure please let me know.

**Comment by 0xcaff** [comment]
Import and export from what?

**Comment by anna-mo** [comment]
@0xcaff Hi there, i also wonder how can i create several accounts?

**Comment by tinybike** [comment]
I'm not sure I understand the question... are you wanting to generate several private keys?  Several private keys + encrypted keystores?  Keythereum doesn't have built-in functions for generating multiple accounts, so you would need to just call the single-account functions multiple times.

**Comment by tinybike** [comment]
Closing this for now.  Feel free to re-open as needed.
