### ISSUE TITLE
Address with Case-Sensitive Checksum

### ISSUE THREAD

**Issue by woodser** [ethereumjs/keythereum#46]
Does keythereum include a way to convert a lowercase addresses to include uppercase letters to verify the checksum?

I'm referring to the checksum algorithm outlined at this link: https://ethereum.stackexchange.com/a/19048

Thanks!

**Comment by fanatid** [comment]
No, but you can do it with ethereumjs-util: https://github.com/ethereumjs/ethereumjs-util/blob/v5.1.3/index.js#L463-L477
