### ISSUE TITLE
How to make browser using faster

### ISSUE THREAD

**Issue by VelMrnk** [ethereumjs/keythereum#48]
I use keythereum.js(without nodejs) in a browser. It works good, but not each time. Almost always the first time the site down and after refreshing the second time keys are created in 10 seconds. For encrypting I use default options. Is it possible to do browser version faster by change default options, like number of cycles or type of coding?

**Comment by tinybike** [comment]
You definitely can speed things up by decreasing the number of rounds, although please be aware that this will make the private key encryption less secure:

- If you're using PBKDF2 (the default) you can change the number of rounds by changing `keythereum.constants.pbkdf2.c`
- If you're using scrypt, you can change the number of rounds by changing `keythereum.constants.scrypt.n`

In both cases, the default number of rounds is `262144`.
