### ISSUE TITLE
RangeError: Array Buffer allocation failed

### ISSUE THREAD

**Issue by subhasisbanik** [ethereumjs/keythereum#53]
I am trying to export key with password passed to the keyethereum module. Code is as below:

 params = {
                keyBytes: 32,
                ivBytes: 16
            };
            options = {
                kdf: "scrypt",
                cipher: "aes-128-ctr",
                kdfparams: {
                    dklen: 32,
                    n: 262144,
                    p: 1,
                    r: 8
                }
            };
            keythereum.create(params, function (dk) {
                keythereum.dump(password, dk.privateKey, dk.salt, dk.iv, options, function (keyObject) {
                    keythereum.exportToFile(keyObject, config.get('Application.envConfig.serverFileLocation'), function (response) {
                        log.info("successfully created new account:" + response);
                        def.resolve({error: undefined, response: response});
                    });
                }, function (err) {
                    log.error("error occured while creating address:" + err);
                    def.reject({error: err.stack, response: undefined });
                });
            }, function (err) {
                log.error("error occured while creating address:" + err);
                def.reject({error: err.stack, response: undefined});
            });

But I am facing:

"RangeError: Array buffer allocation failed",
    "    at new ArrayBuffer (<anonymous>)",
    "    at module.exports (/home/ubuntu/v3/v2-node-latest/node_modules/keythereum/lib/scrypt.js:357:11)",
    "    at Object.deriveKey (/home/ubuntu/v3/v2-node-latest/node_modules/keythereum/index.js:207:18)",
    "    at Object.dump (/home/ubuntu/v3/v2-node-latest/node_modules/keythereum/index.js:394:10)",

**Comment by tinybike** [comment]
Hm, I tried this example and it works for me: https://gist.github.com/tinybike/e5602d2dc474746f427cea39c545dbd0

What environment are you running this in?  What version of Ubuntu?  What version of Node?  How much memory does your computer have?

**Comment by tinybike** [comment]
Closing this for now; feel free to re-open (and specify your environment) if you're still having this issue.
