### ISSUE TITLE
Error: "Unable to resolve module `fs` from...."  when using react native

### ISSUE THREAD

**Issue by bachlongkocanh** [ethereumjs/keythereum#57]
I install keythereum in react native, but when import keythereum then error:

> Unable to resolve module `fs` from '....node_modules/keythereum/lib/scrypt.js`:Module `fs` does not exist in the Haste module map.

How to resolve it.

**Comment by Ayanrocks** [comment]
How you fixed it?

**Comment by arqamali16** [comment]
How to resolve this??

**Comment by ryanio** [comment]
@arqamali16 this should be resolved now, have you tried using v1.2.0?
