### ISSUE TITLE
secure random number generation is not supported by this browser in react native

### ISSUE THREAD

**Issue by bachlongkocanh** [ethereumjs/keythereum#61]
I install lib, when build with debug chrome it work, but build on device or turn off debug then error:

> secure random number generation is not supported by this browser
How to solution??

**Comment by tinybike** [comment]
Unfortunately, I've never tested keythereum with react-native.  Does `crypto.randomBytes` not work in that environment?  If not, you could try swapping in [secure-random](https://www.npmjs.com/package/secure-random) and see if that has whatever polyfill is needed.  (If this works for you, please feel free to submit a PR for it!)

**Comment by tinybike** [comment]
Actually, it appears that secure-random [isn't secure](https://davidgerard.co.uk/blockchain/2018/04/11/javascript-securerandom-isnt-securely-random-most-web-wallets-affected-and-the-bug-was-warned-of-five-years-ago/).  Currently keythereum uses `crypto-browserify`, which uses `crypto.randomBytes` or `window.crypto.getRandomBytes`.  @bachlongkocanh are neither of these available in your environment?  (If not, how are random numbers normally generated in your environment?)

**Comment by bachlongkocanh** [comment]
Use [rn-nodeify](https://github.com/mvayngrib/rn-nodeify) resolve my error.

**Comment by tinybike** [comment]
@bachlongkocanh I'm assuming that means that you've resolved this issue, so I'm closing this for now.  Please reopen if I've misunderstood.
