### ISSUE TITLE
How to check "message authentication code mismatch" function recover

### ISSUE THREAD

**Issue by bachlongkocanh** [ethereumjs/keythereum#62]
I using Asynchronous recover: 

> keythereum.recover(password, keyObject, function (privateKey) {
>   // do stuff
> });

I can't check 'message authentication code mismatch'. how to solution it?

**Comment by tinybike** [comment]
Hm, do you mean that you're getting a message authentication code mismatch error?  If so, that usually means that the password you're providing is incorrect.
