### ISSUE TITLE
Fails to install on node 12

### ISSUE THREAD

**Issue by phahulin** [ethereumjs/keythereum#79]
`npm install keythereum` fails when using node v12

https://gist.github.com/phahulin/3f267d933a5cc78a56b599f6c5d0b8d1

looks like the reason is `scrypt` package

**Comment by bitsanity** [comment]
This is still a problem (Ubuntu) even though this and the linked issue are both closed.

`keythereum` has to update to switch from `scrypt` to node's `crypto` module.

**Comment by Leask** [comment]
This version works, for now: https://github.com/Leask/keythereum .

**Comment by b-m-9** [comment]
This is still a problem (MacOS)
```

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/namepc/.npm/_logs/2020-08-04T21_38_37_227Z-debug.log

```

**Comment by charleenfei** [comment]
i am also receiving this error! would be really cool to merge this pr :)

**Comment by tinybike** [comment]
I just merged @ryanio's PR for this.  Tested it out and everything seems ok on my end, but please re-open this if you encounter further problems.
