### ISSUE TITLE
Getting heapSize error when importing key from file

### ISSUE THREAD

**Issue by nagarwa2** [ethereumjs/keythereum#80]
Library version - 1.0.4
Error message - keythereum/lib/scrypt.js:2431 Linking failure in asm.js: Invalid heap size

**Comment by holgerd77** [comment]
Not sure if this is related to code within the library or rather the surrounding project setup, here is some context article I found on the problem: https://medium.com/chain-accelerator/i-tested-wanchain-125012355b77
