### ISSUE TITLE
Error while accessing ETH wallet

### ISSUE THREAD

**Issue by Kruason** [ethereumjs/keythereum#83]
Hi all. How I can fix this error?

https://prnt.sc/v6ob7o

https://prnt.sc/v6yt6t

**Comment by rumkin** [comment]
Please, provide textual representation of the error here, with all related materials (listings, screenshots, screen recordings, etc).

**Comment by Kruason** [comment]
[info.zip](https://github.com/ethereumjs/keythereum/files/5446357/info.zip)

**Comment by rumkin** [comment]
Could you describe what exactly you do (step-by-step), what do you expect to receive and what do you receive instead? Use [Github Markdown](https://guides.github.com/features/mastering-markdown/) to inline images, code and description of the issue. Please, do not ask others to download something or go to external resources without extra need.

**Comment by holgerd77** [comment]
Will delete all the messages from this issue since this is likely a phishing attempt.
